#include "Pokemons.h"

#include <iostream>
#include <fstream>

#define NUM_POKEMON 150

int readFile()
{
    std::ifstream in;
    std::string line;
    std::string files[NUM_POKEMON] =
        {
            "pokemon/base_stats/bulbasaur.asm",
            "pokemon/base_stats/ivysaur.asm",
            "pokemon/base_stats/venusaur.asm",
            "pokemon/base_stats/charmander.asm",
            "pokemon/base_stats/charmeleon.asm",
            "pokemon/base_stats/charizard.asm",
            "pokemon/base_stats/squirtle.asm",
            "pokemon/base_stats/wartortle.asm",
            "pokemon/base_stats/blastoise.asm",
            "pokemon/base_stats/caterpie.asm",
            "pokemon/base_stats/metapod.asm",
            "pokemon/base_stats/butterfree.asm",
            "pokemon/base_stats/weedle.asm",
            "pokemon/base_stats/kakuna.asm",
            "pokemon/base_stats/beedrill.asm",
            "pokemon/base_stats/pidgey.asm",
            "pokemon/base_stats/pidgeotto.asm",
            "pokemon/base_stats/pidgeot.asm",
            "pokemon/base_stats/rattata.asm",
            "pokemon/base_stats/raticate.asm",
            "pokemon/base_stats/spearow.asm",
            "pokemon/base_stats/fearow.asm",
            "pokemon/base_stats/ekans.asm",
            "pokemon/base_stats/arbok.asm",
            "pokemon/base_stats/pikachu.asm",
            "pokemon/base_stats/raichu.asm",
            "pokemon/base_stats/sandshrew.asm",
            "pokemon/base_stats/sandslash.asm",
            "pokemon/base_stats/nidoranf.asm",
            "pokemon/base_stats/nidorina.asm",
            "pokemon/base_stats/nidoqueen.asm",
            "pokemon/base_stats/nidoranm.asm",
            "pokemon/base_stats/nidorino.asm",
            "pokemon/base_stats/nidoking.asm",
            "pokemon/base_stats/clefairy.asm",
            "pokemon/base_stats/clefable.asm",
            "pokemon/base_stats/vulpix.asm",
            "pokemon/base_stats/ninetales.asm",
            "pokemon/base_stats/jigglypuff.asm",
            "pokemon/base_stats/wigglytuff.asm",
            "pokemon/base_stats/zubat.asm",
            "pokemon/base_stats/golbat.asm",
            "pokemon/base_stats/oddish.asm",
            "pokemon/base_stats/gloom.asm",
            "pokemon/base_stats/vileplume.asm",
            "pokemon/base_stats/paras.asm",
            "pokemon/base_stats/parasect.asm",
            "pokemon/base_stats/venonat.asm",
            "pokemon/base_stats/venomoth.asm",
            "pokemon/base_stats/diglett.asm",
            "pokemon/base_stats/dugtrio.asm",
            "pokemon/base_stats/meowth.asm",
            "pokemon/base_stats/persian.asm",
            "pokemon/base_stats/psyduck.asm",
            "pokemon/base_stats/golduck.asm",
            "pokemon/base_stats/mankey.asm",
            "pokemon/base_stats/primeape.asm",
            "pokemon/base_stats/growlithe.asm",
            "pokemon/base_stats/arcanine.asm",
            "pokemon/base_stats/poliwag.asm",
            "pokemon/base_stats/poliwhirl.asm",
            "pokemon/base_stats/poliwrath.asm",
            "pokemon/base_stats/abra.asm",
            "pokemon/base_stats/kadabra.asm",
            "pokemon/base_stats/alakazam.asm",
            "pokemon/base_stats/machop.asm",
            "pokemon/base_stats/machoke.asm",
            "pokemon/base_stats/machamp.asm",
            "pokemon/base_stats/bellsprout.asm",
            "pokemon/base_stats/weepinbell.asm",
            "pokemon/base_stats/victreebel.asm",
            "pokemon/base_stats/tentacool.asm",
            "pokemon/base_stats/tentacruel.asm",
            "pokemon/base_stats/geodude.asm",
            "pokemon/base_stats/graveler.asm",
            "pokemon/base_stats/golem.asm",
            "pokemon/base_stats/ponyta.asm",
            "pokemon/base_stats/rapidash.asm",
            "pokemon/base_stats/slowpoke.asm",
            "pokemon/base_stats/slowbro.asm",
            "pokemon/base_stats/magnemite.asm",
            "pokemon/base_stats/magneton.asm",
            "pokemon/base_stats/farfetchd.asm",
            "pokemon/base_stats/doduo.asm",
            "pokemon/base_stats/dodrio.asm",
            "pokemon/base_stats/seel.asm",
            "pokemon/base_stats/dewgong.asm",
            "pokemon/base_stats/grimer.asm",
            "pokemon/base_stats/muk.asm",
            "pokemon/base_stats/shellder.asm",
            "pokemon/base_stats/cloyster.asm",
            "pokemon/base_stats/gastly.asm",
            "pokemon/base_stats/haunter.asm",
            "pokemon/base_stats/gengar.asm",
            "pokemon/base_stats/onix.asm",
            "pokemon/base_stats/drowzee.asm",
            "pokemon/base_stats/hypno.asm",
            "pokemon/base_stats/krabby.asm",
            "pokemon/base_stats/kingler.asm",
            "pokemon/base_stats/voltorb.asm",
            "pokemon/base_stats/electrode.asm",
            "pokemon/base_stats/exeggcute.asm",
            "pokemon/base_stats/exeggutor.asm",
            "pokemon/base_stats/cubone.asm",
            "pokemon/base_stats/marowak.asm",
            "pokemon/base_stats/hitmonlee.asm",
            "pokemon/base_stats/hitmonchan.asm",
            "pokemon/base_stats/lickitung.asm",
            "pokemon/base_stats/koffing.asm",
            "pokemon/base_stats/weezing.asm",
            "pokemon/base_stats/rhyhorn.asm",
            "pokemon/base_stats/rhydon.asm",
            "pokemon/base_stats/chansey.asm",
            "pokemon/base_stats/tangela.asm",
            "pokemon/base_stats/kangaskhan.asm",
            "pokemon/base_stats/horsea.asm",
            "pokemon/base_stats/seadra.asm",
            "pokemon/base_stats/goldeen.asm",
            "pokemon/base_stats/seaking.asm",
            "pokemon/base_stats/staryu.asm",
            "pokemon/base_stats/starmie.asm",
            "pokemon/base_stats/mrmime.asm",
            "pokemon/base_stats/scyther.asm",
            "pokemon/base_stats/jynx.asm",
            "pokemon/base_stats/electabuzz.asm",
            "pokemon/base_stats/magmar.asm",
            "pokemon/base_stats/pinsir.asm",
            "pokemon/base_stats/tauros.asm",
            "pokemon/base_stats/magikarp.asm",
            "pokemon/base_stats/gyarados.asm",
            "pokemon/base_stats/lapras.asm",
            "pokemon/base_stats/ditto.asm",
            "pokemon/base_stats/eevee.asm",
            "pokemon/base_stats/vaporeon.asm",
            "pokemon/base_stats/jolteon.asm",
            "pokemon/base_stats/flareon.asm",
            "pokemon/base_stats/porygon.asm",
            "pokemon/base_stats/omanyte.asm",
            "pokemon/base_stats/omastar.asm",
            "pokemon/base_stats/kabuto.asm",
            "pokemon/base_stats/kabutops.asm",
            "pokemon/base_stats/aerodactyl.asm",
            "pokemon/base_stats/snorlax.asm",
            "pokemon/base_stats/articuno.asm",
            "pokemon/base_stats/zapdos.asm",
            "pokemon/base_stats/moltres.asm",
            "pokemon/base_stats/dratini.asm",
            "pokemon/base_stats/dragonair.asm",
            "pokemon/base_stats/dragonite.asm",
            "pokemon/base_stats/mewtwo.asm"};
    // start our engine!
    for (int i = 0; i < NUM_POKEMON; i++)
    {
        in.open(files[i].c_str(), std::fstream::in);
        if (in.is_open())
        {
            std::cout << "reading... " << files[i] << std::endl;
            while (in.good())
            {
                getline(in, line);
                std::cout << line << std::endl;
            }
            in.close();
            std::cout << "SUCCESS" << std::endl;
        }
        else
            std::cout << "Error: unable to open " + files[i] << std::endl;
    }

    return 0;
}
